[options]
; Connexion base de données
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = puerto_db

; Chemins des addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Logs
log_level = info
logfile = /var/lib/odoo/odoo.log

; Performances
workers = 0
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Sécurité
admin_passwd = admin123

; Interface web
http_port = 8069

; Dev
dev_mode = all
